import { PlayerColor } from "../types";

export const EngineInput = {
  UCI: "uci",
  DEBUG: "debug",
  ISREADY: "isready",
  SETOPTION: "setoption",
  REGISTER: "register",
  UCINEWGAME: "ucinewgame",
  POSITION: "position",
  GO: "go",
  STOP: "stop",
  PONDERHIT: "ponderhit",
  QUIT: "quit",
  PERFT: "perft",
  STARTPOS: "startpos",
};

export const EngineOutput = {
  ID: "id",
  UCIOK: "uciok",
  READYOK: "readyok",
  BESTMOVE: "bestmove",
  COPYPROTECTION: "copyprotection",
  REGISTRATION: "registration",
  INFO: "info",
  OPTION: "option",
};

export const Color = {
  WHITE: "w" as PlayerColor,
  BLACK: "b" as PlayerColor,
};

export const Pieces = {
  PAWN: "pawn",
  KNIGHT: "knight",
  BISHOP: "bishop",
  ROOK: "rook",
  QUEEN: "queen",
  KING: "king",
};

export const DefaultFEN =
  "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w - - 0 1";

export const Masks = {
  NOT_A_FILE: BigInt(0xfefefefefefefefe),
  NOT_AB_FILE: BigInt(0xfcfcfcfcfcfcfcfc),
  NOT_GH_FILE: BigInt(0x3f3f3f3f3f3f3f3f),
  NOT_H_FILE: BigInt(0x7f7f7f7f7f7f7f7f),
};

export const Squares = {
  b8: BigInt(2),
  c8: BigInt(3),
  d8: BigInt(4),
  e8: BigInt(5),
  f8: BigInt(6),
  g8: BigInt(7),
  h8: BigInt(8),
  a7: BigInt(9),
  b7: BigInt(10),
  c7: BigInt(11),
  d7: BigInt(12),
  e7: BigInt(13),
  f7: BigInt(14),
  g7: BigInt(15),
  h7: BigInt(16),
  a6: BigInt(17),
  b6: BigInt(18),
  c6: BigInt(19),
  d6: BigInt(20),
  e6: BigInt(21),
  f6: BigInt(22),
  g6: BigInt(23),
  h6: BigInt(24),
  a5: BigInt(25),
  b5: BigInt(26),
  c5: BigInt(27),
  d5: BigInt(28),
  e5: BigInt(29),
  f5: BigInt(30),
  g5: BigInt(31),
  h5: BigInt(32),
  a4: BigInt(33),
  b4: BigInt(34),
  c4: BigInt(35),
  d4: BigInt(36),
  e4: BigInt(37),
  f4: BigInt(38),
  g4: BigInt(39),
  h4: BigInt(40),
  a3: BigInt(41),
  b3: BigInt(42),
  c3: BigInt(43),
  d3: BigInt(44),
  e3: BigInt(45),
  f3: BigInt(46),
  g3: BigInt(47),
  h3: BigInt(48),
  a2: BigInt(49),
  b2: BigInt(50),
  c2: BigInt(51),
  d2: BigInt(52),
  e2: BigInt(53),
  f2: BigInt(54),
  g2: BigInt(55),
  h2: BigInt(56),
  a1: BigInt(57),
  b1: BigInt(58),
  c1: BigInt(59),
  d1: BigInt(60),
  e1: BigInt(61),
  f1: BigInt(62),
  g1: BigInt(63),
  h1: BigInt(64),
};
